on: [push, pull_request]

jobs:
  test:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.24' # The Go version to download (if necessary) and use.
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          skip-cache: true  
      - run: |
          go build
          go test ./...
